# Usa una imagen base de Python oficial
FROM python:3.11-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo requirements.txt en el directorio de trabajo
COPY requirements.txt .

# Instala las dependencias de Python listadas en requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de tu proyecto en el directorio de trabajo
COPY . .

# Expone el puerto que tu aplicación puede usar (si es necesario, aunque en este caso no es estrictamente necesario)
# EXPOSE 8080

# Define el comando por defecto para ejecutar tu script
CMD ["python", "app.py"]
